name: Update Year in README

on:
  schedule:
    - cron: '0 0 1 1 *'  # Run yearly on January 1st
  workflow_dispatch:     # Allow manual runs

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update year in README
        run: |
          current_year=$(date +"%Y")
          sed -i "s/{{YEAR}}/${current_year}/g" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add README.md
          git commit -m "Update year in README to ${current_year}" || echo "No changes to commit"
          git push
